#!/bin/sh

start() {
  if [ -x /usr/bin/mpd -a -f /usr/etc/mpd.conf ] ; then
    echo "starting mpd"
    su mpd -c /usr/bin/mpd
  fi
}

stop() {
  kill `cat /var/run/mpd/pid`
}

status() {
  if pgrep -u mpd mpd > /dev/null 2>&1 ; then
    echo "mpd daemon is running."
    exit 0
  else
    echo "mpd daemon is not running."
    exit 1
  fi
}

case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
restart)
  stop
  sleep 3
  start
  ;;
status)
  status
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|status}"
  exit 1
  ;;
esac
exit 0
